### ISSUE TITLE
Server: Send broadcast message.

### ISSUE THREAD

**Issue by Danila24ru** [KillaMaaki/Netcode.IO.NET#5]
Have this feature?) 
Or should I add RemoteClient in list? 
And how I can use ReliableNetcode with this repo, any example please.

p.s. have you any contact? messanger, forum or?

**Comment by GlaireDaggers** [comment]
Adding clients to/removing from a list and then iterating that list is one way to do that (at least for now). I could also either make the server just expose its internal clientSlots array, or have it keep track of a separate List<RemoteClient> and expose that.
Beyond that a message broadcast is fairly trivial, just iterate each client and send message.
