### ISSUE TITLE
Connect token expired (Linux)

### ISSUE THREAD

**Issue by Danila24ru** [KillaMaaki/Netcode.IO.NET#9]
![time](https://user-images.githubusercontent.com/19823722/30783653-1d12b648-a160-11e7-9364-854104a3b9ba.jpg)

So, I getting error on Linux server when connecting from windows client. What's wrong? 

```C#factory.GenerateConnectToken(ipEndPoint,30, 10, 1, localClientID, new byte[256])```
I see 
```C# 
		/// <summary>
		/// Gets the Unix timestamp of the DateTime object
		/// </summary>
		public static ulong ToUnixTimestamp(this DateTime time)
		{
			return (ulong)Math.Truncate(time.GetTotalSeconds());
		}
```
But where I should use it?

**Comment by Danila24ru** [comment]
UPD: I converted timestamp in this debug to time, there difference in 1 hour, it's uses different time?

**Comment by GlaireDaggers** [comment]
GenerateConnectToken automatically converts the machine's local time to a Unix timestamp - which it does by using DateTime.Now, converting that to a Universal time via ToUniversalTime, and then subtracting a new DateTime( 1970, 1, 1 ) and getting the total seconds.
I'd say try logging the results of DateTime.Now.ToUniversalTime, both on your Windows machine and on your Linux machine, and comparing the two. Also check the system clocks and make sure they're correct.

**Comment by Danila24ru** [comment]
Okay, it's works, I just made asp.net server with token generator on linux.
